// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgmcVMYXjhSbNVcQjDqYkza5ILdUpWTnE',
    appId: '1:968162001724:web:63e810e60f5e43dbc51439',
    messagingSenderId: '968162001724',
    projectId: 'vitacareof',
    authDomain: 'vitacareof.firebaseapp.com',
    storageBucket: 'vitacareof.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2CHAvE0jZw5YhDYreIqi99ExZOzcPTzM',
    appId: '1:968162001724:android:ff6b307f6670c48fc51439',
    messagingSenderId: '968162001724',
    projectId: 'vitacareof',
    storageBucket: 'vitacareof.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARdzUqCJQ1RYnkX7b2xibpI1sP6nXrA2g',
    appId: '1:968162001724:ios:dddc29375a7efdcac51439',
    messagingSenderId: '968162001724',
    projectId: 'vitacareof',
    storageBucket: 'vitacareof.firebasestorage.app',
    iosBundleId: 'com.example.vitacareof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgmcVMYXjhSbNVcQjDqYkza5ILdUpWTnE',
    appId: '1:968162001724:web:2c74460419767349c51439',
    messagingSenderId: '968162001724',
    projectId: 'vitacareof',
    authDomain: 'vitacareof.firebaseapp.com',
    storageBucket: 'vitacareof.firebasestorage.app',
  );

}